# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - "*"  
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write 
  
jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
    
    - name: Download Scripts
      run: |
        wget https://raw.githubusercontent.com/initstring/passphrase-wordlist/master/utilities/cleanup.py
        wget https://raw.githubusercontent.com/initstring/passphrase-wordlist/master/utilities/kym_scrape.py
    
    - name: Download IMB Titles
      run: |
        wget https://datasets.imdbws.com/title.basics.tsv.gz
        gunzip title.basics.tsv.gz
        rm -rf title.basics.tsv.gz
        cat title.basics.tsv | awk -F '\t' '{print $3}' > ./imdb-titles-$(date +%Y-%m-%d).txt
        rm title.basics.tsv
   
    - name: Combining
      run: |
       cat ./*.txt | sort -u > passphrases.txt
       
 

    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "passphrases.txt"
        bodyFile: "body.md"
