# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    tags:
      - "v*"  

  pull_request:
    branches: [ "main" ]

jobs:
  Download:
    runs-on: ubuntu-latest
    permissions:
      contents: write        
    
    steps:
    - name: Download Scripts
      run: |
        wget https://raw.githubusercontent.com/initstring/passphrase-wordlist/master/utilities/cleanup.py
        wget https://raw.githubusercontent.com/initstring/passphrase-wordlist/master/utilities/kym_scrape.py
    
    - name: Download IMB Titles
      run: |
        wget https://datasets.imdbws.com/title.basics.tsv.gz
        gunzip title.basics.tsv.gz
        rm -rf title.basics.tsv.gz
        cat title.basics.tsv | awk -F '\t' '{print $3}' > ./imdb-titles-$(date +%Y-%m-%d).txt
        rm title.basics.tsv
   
    - name: Combining
      run: |
       cat ./*.txt | sort -u > passphrases.txt

    
 
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: echo ${{ github.sha }} > Release.txt
    - name: Test
      run: cat Release.txt
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: Release.txt
        retention-days: 5    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Release.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
