# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - "*"  
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write'
  
jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
    
    - name: Download Scripts
      run: |
        wget https://raw.githubusercontent.com/initstring/passphrase-wordlist/master/utilities/cleanup.py
        wget https://raw.githubusercontent.com/initstring/passphrase-wordlist/master/utilities/kym_scrape.py
    
    - name: Download IMB Titles
      run: |
        wget https://datasets.imdbws.com/title.basics.tsv.gz
        gunzip title.basics.tsv.gz
        rm -rf title.basics.tsv.gz
        cat title.basics.tsv | awk -F '\t' '{print $3}' > ./imdb-titles-$(date +%Y-%m-%d).txt
        rm title.basics.tsv
   
    - name: Combining
      run: |
       cat ./*.txt | sort -u > raw.txt
       python3 ./cleanup.py raw.txt passphrases.txt
    
    - name: Create Gitbun Release  
      uses: actions/create-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      with:
        tag_name: ${{ github.run_number }}
        release_name: ${{ github.run_number }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ env.CHANGELOG_FILE }}
        append_body: true
        files: |
          passphrases.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
