# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    tags:
      - "v*"  

  pull_request:
    branches: [ "main" ]

jobs:
  Download_Script:
    runs-on: ubuntu-latest
    permissions:
      contents: write        
    
    steps:    
    - name: Download Scripts    
      run: |
        mkdir -p scripts
        wget https://raw.githubusercontent.com/initstring/passphrase-wordlist/master/utilities/cleanup.py -O ./scripts/cleanup.py
        wget https://raw.githubusercontent.com/initstring/passphrase-wordlist/master/utilities/kym_scrape.py -O ./scripts/kym_scrape.py
    - uses: actions/upload-artifact@v3
      with:
        name: Script-artifact
        path: scripts/*.py  
  
  Download-IMDB-and-Wikipedia: 
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:   
    - name: Download IMB Titles
      run: |
        mkdir -p files
        wget https://datasets.imdbws.com/title.basics.tsv.gz
        gunzip title.basics.tsv.gz
        rm -rf title.basics.tsv.gz
        cat title.basics.tsv | awk -F '\t' '{print $3}' > ./files/imdb-titles-$(date +%Y-%m-%d).txt
        rm title.basics.tsv
    - uses: actions/upload-artifact@v3
      with:
        name: Password-artifact
        path: files/imdb-titles-*.txt          

    - name: Wikipedia article titles & category names
      run: |   
        mkdir -p files
        wget https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles-multistream-index.txt.bz2
        bzip2 -d ./enwiki-latest-pages-articles-multistream-index.txt.bz2
        cat ./enwiki-latest-pages-articles-multistream-index.txt | cut -d: -f 3 > ./files/wikipedia-$(date +%Y-%m-%d).txt
        rm enwiki-latest-pages-articles-multistream-index.txt
    - uses: actions/upload-artifact@v3
      with:
        name: Password-artifact
        path: files/wikipedia-*.txt            

  Download-Urban-Dictionary: 
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:    
    - name: Urban Dictionary
      run: | 
        mkdir -p files
        git clone https://github.com/initstring/urban-dictionary-word-list
        cd urban-dictionary-word-list
        touch urban-dictionary-$(date +%Y-%m-%d).txt
        pip3 install bs4 
        python3 ./main.py --out ./files/urban-dictionary-$(date +%Y-%m-%d).txt
    - uses: actions/upload-artifact@v3
      with:
        name: Password-artifact
        path: files/urban-dictionary-*.txt  
        
  Download-Meme: 
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    needs: [Download_Script]
    steps:    
    - uses: actions/download-artifact@master
      with:
        name: Script-artifact
        path: ./       
    - name: Know Your Meme
      run: |  
        mkdir -p files
        python3 kym_scrape.py
        mv memes.txt ./files/know-your-meme-$(date +%Y-%m-%d).txt
    - uses: actions/upload-artifact@v3
      with:
        name: Password-artifact
        path: files/know-your-meme-*.txt     

  Download-Global-POI: 
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps: 
    - name: Global POI dataset
      run: | 
        wget http://download.geonames.org/export/dump/allCountries.zip
        unzip ./allCountries.zip
        cat allCountries.txt | awk -F '\t' '{print $3}' > ./files/global-poi-$(date +%Y-%m-%d).txt
        rm allCountries.zip
        rm allCountries.txt
    - uses: actions/upload-artifact@v3
      with:
        name: Password-artifact
        path: files/global-poi-*.txt          
  
  Download-Billboard: 
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps: 
    - name: Billboard Download
      run: | 
        git clone https://github.com/Bl4d3666/umdmusic-downloader
        cd umdmusic-downloader
        pip3 install -r ./requirements.txt
        python3 ./downloader.py
        cat ./us_billboard.psv | cut -d "|" -f 5 > ./billboard-titles-$(date +%Y-%m-%d).txt
        cat ./us_billboard.psv | cut -d "|" -f 6 | sed "s/ featuring /\n/g" > ./files/billboard-artists-$(date +%Y-%m-%d).txt
        rm ./us_billboard.psv
    - uses: actions/upload-artifact@v3
      with:
        name: Password-artifact
        path: files/billboard-artists-*.txt          
          
  Download-Combining: 
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    needs: [Download_Script,Download-IMDB-and-Wikipedia, Download-Urban-Dictionary, Download-Meme,Download-Global-POI,Download-Billboard]
    steps: 
    - uses: actions/download-artifact@master
      with:
        name: Password-artifact
        path: ./      
    - name: Combining
      run: |
       cat ./*.txt | sort -u > passphrases.txt
       python3 ./cleanup.py raw.txt passphrases.txt
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Password Phrases"
        files: passphrases.txt
